### ISSUE TITLE
Crash on bad ZIP code

### ISSUE THREAD

**Issue by lynt-smitka** [MonkeyData/php-opencart-xml-feed-generator#2]
There were 2 wrong ZIP codes in our case (swapped City name and ZIP code). Module stopped at https://github.com/MonkeyData/php-opencart-xml-feed-generator/blob/master/admin/XmlGenerator/Model/XmlModel.php#L207
and produced incomplete XML.

**Comment by MonkeyData** [comment]
Thank you for your feedback, we already fixed it. MD
